= VLC Docker Container Virtual Lab

== Authors

* Aristotelis Sifakis ice20390213 
* Christos Pylarinos ice20390278 
* Nikos Georgiou ice20390298 
* Giorgos Santos ice20390204

== Introduction

This Docker container runs VLC media player in a headless environment using Xvfb (X virtual framebuffer) to play a local video file. This setup is useful for scenarios where graphical output is needed in a headless Linux environment.

== Prerequisites

* Docker installed on your system. If not installed, follow the instructions at link:https://docs.docker.com/get-docker/[https://docs.docker.com/get-docker/]
* Basic familiarity with Docker commands and Linux shell.

== Installation

1. Clone the Repository:

[source,sh]
----
git clone https://github.com/aristotelissifakis/Cloud
cd vlc-docker
----

2. Build the Docker Image:

[source,sh]
----
docker build -t vlc-container .
----

3. Run the Docker Container:

[source,sh]
----
docker run --rm -it \
  --device /dev/snd \
  --device /dev/dri \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e DISPLAY=$DISPLAY \
  vlc-container
----

This command starts the Docker container with VLC playing the `video.mp4` file in fullscreen mode.

== Notes

* Ensure that your system supports Docker and has necessary permissions for audio and video devices.
* For headless environments without X11, Xvfb is used to simulate a display.
